### ISSUE TITLE
can't find babel-core/browser-polyfill.js

### ISSUE THREAD

**Issue by myusrn** [cveld/AsyncAwait-TypeScript-Example#1]
after executing "npm install gulp-babel --save-dev" i'm unable to find the './node_modules/gulp-babel/node_modules/babel-core/browser-polyfill.js' file or simply 'browser-polyfill.js' anywhere under that package folder.   Has it been moved in the current "gulp-babel": "^6.1.2" package?

also have you tried using this solution within an apache cordova project environment where angular2 is enabled to get support for async/await working there?

**Comment by cveld** [comment]
@myusrn Were you able to solve your issue in the meantime?

**Comment by cveld** [comment]
@myusrn Were you able to solve the issue in the meanwhile? Apologies for not tracking this issue!

**Comment by myusrn** [comment]
@cveld thanks for the followup, i can't remember its been so long. I'll close this issue because none of the scenario is still relevant with typescript now having async/await support and spa frameworks being used having changed.
